/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.5.1/userguide/multi_project_builds.html
 */

rootProject.name = "lisao"
include("junit5")
include("core")
include("spring")
include("alg")
include("springboot")
include("rocketmq")
include("thirdlibrary")
include("mybatis")
include("tomcat")
include("self-mvc")
include("compile")
include("redis")
include("netty")
include("disruptor")
